# Generated by Django 4.1.4 on 2023-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_autor_alter_post_date_alter_post_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emitter', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
