# Generated by Django 4.1.4 on 2023-01-02 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mensaje_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
